### ISSUE TITLE
crear metodo identify(string)

### ISSUE THREAD

**Issue by pedrog31** [pedrog31/Prueba-de-software#8]
detecta invalidadores de conteo (llama a String detectString (string) comillas dobles (strings), String detectComent (strings) signos para comentarios)
El método identifica tipo de sentencia,
llamar al contador de lineas y el resultado sumarlo a la cuenta que se lleve

**Comment by danielospinap** [comment]
Revisar si el string que devuelve detectComent es diferente al que se envió
